### ISSUE TITLE
Класс котов

### ISSUE THREAD

**Issue by lalalaoalla** [lalalaoalla/the-beginning-of-object-oriented-programming#1]
Добавлен класс котов, в классе Human добавились функции взять кошку
1) я могу передать параметром только имя кошки, а как сделать так тогда чтобы в дальнейшем я смогла работать в других функциях с этим?
2) почему в передаче всего объекта house тогда нет проблем?
я запуталась((((
[класс котов.md](https://github.com/user-attachments/files/15910464/default.md)

**Comment by daniil225** [comment]
Испаравь следующий момент. Так делать крайне не желательно. Это может привести к тому, что в один момент ты забудешь изменить состояние и получишь **ооочень** сложно уловимую ошибку
![image](https://github.com/lalalaoalla/the-beginning-of-object-oriented-programming/assets/31102560/22a1575b-bae1-42be-ab26-ad5098a47a3c)

**Comment by lalalaoalla** [comment]
Типа того?
![image](https://github.com/lalalaoalla/the-beginning-of-object-oriented-programming/assets/162860805/9d7e6b10-bc41-481f-b0d5-384e46cb728c)

**Comment by daniil225** [comment]
Здесь не совсем понятно, а кто такой объект `House` , а если их будет 2 и более как его выбрать. Если у тебя некоторый объект выступает как некоторая зависимость, то хорошим, но не единственно верным, будет передавать его как зависимость. То есть прототип функции будет выглядеть как то так:
```python
def take_a_cat(self, nickname, house:House):
     # твоя реализация
     # ...
     house.count_cats+=1
```
в таком исполнении твой класс не будет привязан к конкретному дому, и позволит создать например список домов, где будут свои жильцы и прочее

**Comment by lalalaoalla** [comment]
То есть ты предлагаешь, чтобы счетчик был атрибутом объекта, а не класса?

**Comment by daniil225** [comment]
Нет. Нужно понять, что класс - это некоторая завершенная сущность, и при ее создании и использовании методов, не нужно в ручную контролировать его состояние. Этими вещами должен заниматься вызываемый метод

**Comment by lalalaoalla** [comment]
Такс, вызываемый метод - взять кошку в дом, или заехать, количество жителей\количество животных в доме увеличилось, у вызываемого метода, или я чего-то не понимаю
![image](https://github.com/lalalaoalla/the-beginning-of-object-oriented-programming/assets/162860805/6c7162c8-e3e2-46f0-b57f-b844490e3e85)

**Comment by lalalaoalla** [comment]
Класс House сейчас выглядит вот так
![image](https://github.com/lalalaoalla/the-beginning-of-object-oriented-programming/assets/162860805/1d0c0551-cb75-4ffe-b562-feee4de13d0a)

**Comment by lalalaoalla** [comment]
Класс House сейчас выглядит вот так

![image](https://github.com/lalalaoalla/the-beginning-of-object-oriented-programming/assets/162860805/1d0c0551-cb75-4ffe-b562-feee4de13d0a)

**Comment by daniil225** [comment]
Стало немного лучше. Но все равно есть еще очень большой недостаток. 

Все что дальше - это рекомендации и не нужно их сейчас применять к этому проекту. Его предлагаю закрыть, а в новом уже учесть недочеты и сделать лучше

У тебя в классе Human объект House передается как некоторая зависимость, и получается у тебя как бы дом находится в классе человек. Казалось бы вроде логично, но а если в доме живут 5 человек, получается что у тебя будет один класс дом для всех пятерых. Но здесь идет нарушение принципа содержания одного объекта в другом. По сути у тебя дом содержит жильцов. И было бы логично сделать так, что бы в классе House был например массив объектов Human, что решило бы кучу проблем. Во первых не нужно было бы следить за переменной количества жильцов (у тебя это в точности размер массива жильцов). Один и тот же человек смог бы жить в не только в одном доме а сразу в 2-х и более. Такая небольшая модификация позволит сделать систему более расширяемой и  легкой в сопровождении. 

С классом котов все примерно так же, только кот (если он домашний, а не бездомный) принадлежит человеку. Поэтому разумно, что бы кот **содержался** в классе человек. 

О том почему я так предлагаю сделать. У тебя на лицо отношение между классами - класс А **содержится** в классе В. Если бы между ними нельзя было поставить подобного соответствия, то нужно было бы применять другие подходы к организации взаимодействия 

- Например наследование - **отношение является**
- **Использует**, когда объект использует для своих нужд какой-то другой. Например ПК использует лазерный принтер, но вот наоборот не имеет смысла это делать. 
- **Реализован как**, когда объект реализуется внутри по средствам какой-либо другой технологии. Например Стек можно реализовать на основе списка.
